### DISCUSSION TITLE
ntfy-sh-with-homeassistant

### DISCUSSION THREAD

**Discussion by diecknet-discussions** [diecknet/diecknet-blog#309] [Blog Discussions]
# ntfy-sh-with-homeassistant

Just a quick note if you want to use ntfy.sh with Home Assistant.
Setup I added the following section to my /config/configuration.yaml file:
1 2 3 4 5 6 7 8 9 10 11 12 13 shell_command: ntfy: > curl -X POST --url 'https://ntfy.sh/{{ topic }}' --data '{{ message }}' --header 'X-Title: {{ title }}' --header 'X-Tags: {{ tags }}' --header 'X-Priority: {{ priority }}' --header 'X-Delay: {{ delay }}' --header 'X-Actions: {{ actions }}' --header 'X-Click: {{ click }}' --header 'X-Icon: {{ icon }}'{% endraw %} Usage To send send a notification, I use this YAML action in an Automation.

https://diecknet.de/en/2023/02/12/ntfy-sh-with-homeassistant/

**Comment by dgmltn** [comment]
Or how about using `rest_command` instead of `shell_command`?
```
rest_command:
  ntfy:
    method: POST
    url: 'https://ntfy.sh/{{ topic }}'
    headers:
      X-Title: '{{ title }}'
      X-Tags: '{{ tags }}'
      X-Priority: '{{ priority }}'
      X-Delay: '{{ delay }}'
      X-Actions: '{{ actions }}'
      X-Click: '{{ click }}'
      X-Icon: '{{ icon }}'
    payload: '{{ message }}'
```
